export const ukBanks: string[] = [
  'HSBC',
  'Barclays',
  'Lloyds Banking Group',
  'NatWest Group',
  'Standard Chartered',
  'Santander UK',
  'Nationwide Building Society',
  'Virgin Money UK',
  'The Co-operative Bank',
  'Metro Bank',
  'Monzo Bank',
  'Starling Bank',
  'Revolut',
  'Tesco Bank',
  'Clydesdale Bank',
  'Bank of Scotland',
  'Halifax',
];
